### ISSUE TITLE
Null pointer exception when clicked on Save button after marking Short

### ISSUE THREAD

**Issue by rohan-morje** [ajency/HK-Issue-Tracker#1448]
Create GRN Inventory Checkin - GRN# 1513395 (PO# 1820467)
Do inventory checking - NUT304-10 (2 checkin out of 2 qty)
NUT304-27 (2 checkin out of 3 qty)
Select Select Grn item checkbox and click on Create Extra Inventory button -> Will navigate to
Enter the Recieve qty, , click on Short button and click on Save button and observe

Actual result: Null pointer exception when clicked on Save button after marking Short

![image](https://user-images.githubusercontent.com/14803102/78326030-f984de00-7596-11ea-956f-922f89f06d91.png)

![image](https://user-images.githubusercontent.com/14803102/78326054-043f7300-7597-11ea-9a30-b563ae98bee3.png)

**Comment by Shraddhar23** [comment]
Exists on master for HK Aqua WH 5.0

**Comment by Shraddhar23** [comment]
resolved

**Comment by rohan-morje** [comment]
This issue is still present
![image](https://user-images.githubusercontent.com/14803102/78966524-c1911400-7b1d-11ea-98ec-49bc66370c09.png)

**Comment by Shraddhar23** [comment]
The extra line item should be saved first and then create short of it.

**Comment by Shraddhar23** [comment]
![Screenshot 2020-04-10 at 5 44 58 PM](https://user-images.githubusercontent.com/48199171/78990086-1f8c1e80-7b53-11ea-8858-c4419eb45c53.png)
![Screenshot 2020-04-10 at 5 45 17 PM](https://user-images.githubusercontent.com/48199171/78990089-22870f00-7b53-11ea-8e6f-1af2dc52528a.png)

**Comment by rohan-morje** [comment]
Issue resolved
