### ISSUE TITLE
Product variant filter applied gets cleared on navigating to the other results pages.

### ISSUE THREAD

**Issue by larissa-c-d** [ajency/HK-Issue-Tracker#798]
Actual Result
Product variant filter applied gets cleared on navigating to the other results page.

Expected results
Product variant filter applied should not be cleared , when navigating to the other results pages.

Screenshot
![image](https://user-images.githubusercontent.com/54023516/70037231-3e463b80-15dc-11ea-8ea0-9bf67b4b5b21.png)
![image](https://user-images.githubusercontent.com/54023516/70038151-d264d280-15dd-11ea-9d29-d1b1e471219a.png)

**Comment by legred21** [comment]
Fixed

**Comment by larissa-c-d** [comment]
Issue still exists
![12⁄16⁄1913:13:49](https://user-images.githubusercontent.com/54023516/70888322-14dad600-2006-11ea-8b03-40e915b27771.png)

![image](https://user-images.githubusercontent.com/54023516/70888278-fc6abb80-2005-11ea-8265-c6f5003ff7fd.png)

**Comment by legred21** [comment]
Fixed
![image](https://user-images.githubusercontent.com/55079454/70892365-0cd36400-200f-11ea-9ef3-496fcd913fa8.png)

![image](https://user-images.githubusercontent.com/55079454/70892479-41472000-200f-11ea-95ea-8997fd521dbd.png)

**Comment by larissa-c-d** [comment]
Issue resolved
